services:
  python_control:
    container_name: python_control
    build:
      context: .
      dockerfile: ./docker/python_control/Dockerfile
    restart: always
    volumes:
      - ./services/python_control:/python_control
    stdin_open: true
    tty: true
    ports:
      - "8887:8887"
